name: 'Addon-Hyperion-NG'

# Controls when the action will run
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installs Node JS
      - uses: actions/setup-node@v4

      # Sync version to source
      - run: ./.github/scripts/update-hyperion-version.sh

      # Docker login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push Docker images
      - name: Build and push Docker images
        run: |
          ./.github/scripts/build.sh amd64
          docker tag my-image:amd64 myusername/my-repo:amd64
          docker push myusername/my-repo:amd64

          ./.github/scripts/build.sh armhf
          docker tag my-image:armhf myusername/my-repo:armhf
          docker push myusername/my-repo:armhf

          ./.github/scripts/build.sh aarch64
          docker tag my-image:aarch64 myusername/my-repo:aarch64
          docker push myusername/my-repo:aarch64

      - uses: test-room-7/action-update-file@v1
        if: ${{ env.VERSION != env.RELEASE }}
        with:
          file-path: addon-hyperion-ng/config.json
          commit-msg: Update version
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.14.0
        if: ${{ env.VERSION != env.RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: true
