name: 'Addon-Hyperion-NG'

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: ./.github/scripts/update-hyperion-version.sh

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and Push Docker Image (amd64)
      - name: Build and Push Docker Image (amd64)
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            -t ghcr.io/${{ github.repository | toLower }}/hyperion-ng-addon-amd64:${{ env.VERSION }} \
            -t ghcr.io/${{ github.repository | toLower }}/hyperion-ng-addon-amd64:latest \
            --push .

      # Build and Push Docker Image (armhf)
      - name: Build and Push Docker Image (armhf)
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm/v7 \
            -t ghcr.io/${{ github.repository | toLower }}/hyperion-ng-addon-armhf:${{ env.VERSION }} \
            -t ghcr.io/${{ github.repository | toLower }}/hyperion-ng-addon-armhf:latest \
            --push .

      # Build and Push Docker Image (aarch64)
      - name: Build and Push Docker Image (aarch64)
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64/v8 \
            -t ghcr.io/${{ github.repository | toLower }}/hyperion-ng-addon-aarch64:${{ env.VERSION }} \
            -t ghcr.io/${{ github.repository | toLower }}/hyperion-ng-addon-aarch64:latest \
            --push .

      - uses: test-room-7/action-update-file@v1
        if: ${{ env.VERSION != env.RELEASE }}
        with:
          file-path: addon-hyperion-ng/config.json
          commit-msg: Update version
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.14.0
        if: ${{ env.VERSION != env.RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: true
