name: 'Addon-Hyperion-NG'

on:
  workflow_dispatch:
    # This workflow runs when manually triggered via the "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Adjust timeout as necessary

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: ./.github/scripts/update-hyperion-version.sh

      - shell: bash
        run: |
          ./.github/scripts/build.sh amd64 &&
          ./.github/scripts/build.sh armhf &&
          ./.github/scripts/build.sh aarch64

      - uses: test-room-7/action-update-file@v1
        if: ${{ env.VERSION != env.RELEASE }}
        with:
          file-path: addon-hyperion-ng/config.json
          commit-msg: Update version
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into GitHub Packages Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Tag and push Docker image to GitHub Packages
        run: |
          docker tag bradsjm/hyperion-ng-addon-amd64:2.0.16 docker.pkg.github.com/${{ github.repository_owner }}/addon-hyperion-ng/hyperion-ng-addon-amd64:2.0.16
          docker push docker.pkg.github.com/${{ github.repository_owner }}/addon-hyperion-ng/hyperion-ng-addon-amd64:2.0.16
