name: 'Addon-Hyperion-NG'

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Sync version to source
        run: ./.github/scripts/update-hyperion-version.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        run: |
          ./.github/scripts/build.sh amd64
          docker tag my-image:amd64 myusername/my-repo:amd64
          docker push myusername/my-repo:amd64

          ./.github/scripts/build.sh armhf
          docker tag my-image:armhf myusername/my-repo:armhf
          docker push myusername/my-repo:armhf

          ./.github/scripts/build.sh aarch64
          docker tag my-image:aarch64 myusername/my-repo:aarch64
          docker push myusername/my-repo:aarch64

      - name: Retry Docker push on failure
        run: |
          retry=0
          until docker push myusername/my-repo:amd64 || [ $retry -eq 3 ]
          do
            retry=$((retry+1))
            sleep 30
          done

      - name: Update version in config.json
        if: ${{ env.VERSION != env.RELEASE }}
        uses: test-room-7/action-update-file@v1
        with:
          file-path: addon-hyperion-ng/config.json
          commit-msg: Update version
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        if: ${{ env.VERSION != env.RELEASE }}
        uses: ncipollo/release-action@v1.14.0
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
